import type { Skill, SkillMapPreviewData, SkillModule, SkillPrerequisite } from "./skill-types";

/*
 * This seed mirrors supabase/migrations/20260612011000_create_skill_map.sql.
 * It is the source of truth for the read-only dashboard preview when the
 * Supabase skill migration has not been applied yet, and it keeps stable
 * skill ids aligned with docs/SKILL_ENGINE.md.
 *
 * Keep this file and the SQL migration in lockstep: the seed-integrity unit
 * tests guard structure, but the two must agree on ids, modules, and order.
 */

export const skillModules: SkillModule[] = [
  { id: "cpp.program_basics", title: "Program basics", description: "Program structure and console I/O.", order_index: 2 },
  { id: "cpp.values_types", title: "Values and types", description: "Variables, types, and conversions.", order_index: 4 },
  { id: "cpp.control_flow", title: "Control flow", description: "Conditionals and loops.", order_index: 6 },
  { id: "cpp.functions", title: "Functions", description: "Declarations, parameters, and decomposition.", order_index: 8 },
  { id: "cpp.references", title: "References, pointers, and const", description: "Aliases, addresses, const-correctness, and parameter passing.", order_index: 9 },
  { id: "cpp.structs_classes", title: "Structs and classes", description: "Members and access control.", order_index: 10 },
  { id: "cpp.constructors", title: "Constructors", description: "Object initialization and lifetime.", order_index: 20 },
  { id: "cpp.raii", title: "RAII", description: "Resource ownership and cleanup.", order_index: 30 },
  { id: "cpp.smart_pointers", title: "Smart pointers", description: "Modern ownership helpers.", order_index: 40 },
  { id: "cpp.stl", title: "STL containers", description: "Everyday standard-library containers.", order_index: 50 },
  { id: "dsa.arrays", title: "Arrays and sequences", description: "Indexing and traversal fundamentals.", order_index: 110 },
  { id: "dsa.searching", title: "Searching", description: "Finding values efficiently.", order_index: 120 },
  { id: "dsa.sorting", title: "Sorting", description: "Ordering with comparators.", order_index: 130 },
  { id: "dsa.stacks", title: "Stacks and queues", description: "LIFO and FIFO problem patterns.", order_index: 140 },
  { id: "dsa.hashing", title: "Hashing", description: "Hash maps and sets for fast lookup.", order_index: 150 },
  { id: "dsa.recursion", title: "Recursion", description: "Base cases and recursive structure.", order_index: 160 }
];

export const skillSeed: Skill[] = [
  {
    id: "cpp.program_basics.structure",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Program structure and main()",
    description: "Read a minimal program: includes, main(), statements, and return values.",
    learner_goal: "Explain where a program starts and what main()'s return value means.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 1,
    is_active: true
  },
  {
    id: "cpp.program_basics.io",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Console input and output",
    description: "Print with std::cout and read with std::cin.",
    learner_goal: "Write output and read input using the iostream operators.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 2,
    is_active: true
  },
  {
    id: "cpp.values_types.variables",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Variables, types, and initialization",
    description: "Declare and initialize variables of the fundamental types.",
    learner_goal: "Choose a fundamental type, initialize on declaration, and use auto/const.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 3,
    is_active: true
  },
  {
    id: "cpp.values_types.conversions",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Conversions and casts",
    description: "Understand truncation, narrowing, and static_cast.",
    learner_goal: "Predict the result of a numeric conversion and cast explicitly with static_cast.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 4,
    is_active: true
  },
  {
    id: "cpp.control_flow.conditionals",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Conditionals",
    description: "Branch with if/else and switch using comparison and logical operators.",
    learner_goal: "Write correct if/else and switch logic and avoid switch fall-through.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 5,
    is_active: true
  },
  {
    id: "cpp.control_flow.loops",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Loops",
    description: "Repeat with for/while and control flow with break/continue.",
    learner_goal: "Write a loop that runs the right number of times and avoid off-by-one errors.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 6,
    is_active: true
  },
  {
    id: "cpp.functions.basics",
    domain: "cpp",
    module_id: "cpp.functions",
    title: "Function basics",
    description: "Declare functions with parameters, return values, and local scope.",
    learner_goal: "Write and call a function, and explain where its local variables live.",
    level: "beginner",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 7,
    is_active: true
  },
  {
    id: "cpp.functions.decomposition",
    domain: "cpp",
    module_id: "cpp.functions",
    title: "Decomposition and headers",
    description: "Split work into small functions and across header/source files.",
    learner_goal: "Break a task into small, well-named functions and place declarations in a header.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 8,
    is_active: true
  },
  {
    id: "cpp.references.references",
    domain: "cpp",
    module_id: "cpp.references",
    title: "References",
    description: "Use lvalue references as aliases for existing objects.",
    learner_goal: "Bind a reference and use it to modify the caller's object.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 90,
    is_active: true
  },
  {
    id: "cpp.references.pointers",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Pointers and nullptr",
    description: "Hold addresses, dereference safely, and handle nullptr.",
    learner_goal: "Take an address, dereference a pointer, and avoid null dereferences.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 91,
    is_active: true
  },
  {
    id: "cpp.references.const_correctness",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Const correctness",
    description: "Use const to express and enforce read-only intent.",
    learner_goal: "Apply const to parameters and methods to prevent accidental modification.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 92,
    is_active: true
  },
  {
    id: "cpp.references.parameter_passing",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Parameter passing",
    description: "Choose by-value, const-reference, or reference for parameters.",
    learner_goal: "Pass small types by value, large read-only types by const reference, and outputs by reference.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 93,
    is_active: true
  },
  {
    id: "cpp.structs_classes.syntax",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Struct/class syntax",
    description: "Define simple structs and classes with member fields and methods.",
    learner_goal: "Write a small type and explain how objects are created from it.",
    level: "beginner",
    item_types: ["lesson", "fill_blank", "code_reading"],
    order_index: 10,
    is_active: true
  },
  {
    id: "cpp.structs_classes.public_private",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Public and private access",
    description: "Use access control to protect object state and understand compiler access errors.",
    learner_goal: "Decide which members should be public or private and fix simple access mistakes.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting", "code_reading"],
    order_index: 20,
    is_active: true
  },
  {
    id: "cpp.structs_classes.const_methods_intro",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Const methods intro",
    description: "Read const method declarations and understand why const objects need const-safe methods.",
    learner_goal: "Predict whether a method call on a const object should compile.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting"],
    order_index: 30,
    is_active: true
  },
  {
    id: "cpp.structs_classes.invariants_intro",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Class invariants intro",
    description: "Explain how classes maintain valid state through constructors and member functions.",
    learner_goal: "Describe the rule that must stay true for an object after every public method.",
    level: "beginner",
    item_types: ["lesson", "concept_check"],
    order_index: 40,
    is_active: true
  },
  {
    id: "cpp.constructors.default_constructor",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Default constructor",
    description: "Explain and write a constructor with no arguments.",
    learner_goal: "Create an object with safe default state.",
    level: "beginner",
    item_types: ["lesson", "fill_blank"],
    order_index: 110,
    is_active: true
  },
  {
    id: "cpp.constructors.parameterized_constructor",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Parameterized constructor",
    description: "Initialize object state through constructor arguments.",
    learner_goal: "Use constructor parameters to make invalid states harder to create.",
    level: "beginner",
    item_types: ["lesson", "code_reading"],
    order_index: 120,
    is_active: true
  },
  {
    id: "cpp.constructors.member_initializer_list",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Member initializer list",
    description: "Use initializer lists and explain why they are preferred for direct initialization.",
    learner_goal: "Choose an initializer list over assignment inside the constructor body.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting"],
    order_index: 130,
    is_active: true
  },
  {
    id: "cpp.constructors.destructor_intro",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Destructor intro",
    description: "Explain when destructors run and why they matter for resources.",
    learner_goal: "Predict the lifetime order of simple stack objects.",
    level: "beginner",
    item_types: ["lesson", "predict_output"],
    order_index: 140,
    is_active: true
  },
  {
    id: "cpp.raii.resource_lifetime",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Resource lifetime",
    description: "Connect resource acquisition to object lifetime.",
    learner_goal: "Explain why the object that owns a resource should release it automatically.",
    level: "intermediate",
    item_types: ["lesson", "concept_check"],
    order_index: 210,
    is_active: true
  },
  {
    id: "cpp.raii.destructor_cleanup",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Destructor cleanup",
    description: "Use destructors to release resources when ownership is manual.",
    learner_goal: "Read a wrapper type and identify the cleanup point.",
    level: "intermediate",
    item_types: ["lesson", "code_reading"],
    order_index: 220,
    is_active: true
  },
  {
    id: "cpp.raii.exception_safety_intro",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Exception safety intro",
    description: "Explain why RAII helps when code exits early because of return or exception.",
    learner_goal: "Recognize why cleanup should not depend on reaching the last line of a function.",
    level: "intermediate",
    item_types: ["quiz", "code_reading"],
    order_index: 230,
    is_active: true
  },
  {
    id: "cpp.raii.ownership_boundary",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Ownership boundary",
    description: "Identify which object owns a resource and which code only observes it.",
    learner_goal: "Draw the boundary between owner and non-owner in small examples.",
    level: "intermediate",
    item_types: ["quiz", "bug_spotting"],
    order_index: 240,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.unique_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "unique_ptr",
    description: "Use unique ownership and explain why unique_ptr cannot be copied.",
    learner_goal: "Transfer ownership with move and avoid accidental shared ownership.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 310,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.shared_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "shared_ptr",
    description: "Explain shared ownership and reference counting at a beginner-friendly level.",
    learner_goal: "Identify when multiple objects intentionally share ownership.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 320,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.weak_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "weak_ptr",
    description: "Explain non-owning observation and cyclic-reference prevention.",
    learner_goal: "Recognize when a pointer should observe without extending lifetime.",
    level: "intermediate",
    item_types: ["lesson", "code_reading"],
    order_index: 330,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.cyclic_reference",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Cyclic references",
    description: "Spot a shared_ptr cycle and explain why it leaks.",
    learner_goal: "Break a cycle by changing one side to weak_ptr.",
    level: "intermediate",
    item_types: ["bug_spotting", "code_reading"],
    order_index: 340,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.ownership_choice",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Choosing the right ownership",
    description: "Decide between a stack object, a value member, a non-owning reference, and a smart pointer.",
    learner_goal: "Pick the simplest ownership that works, and avoid reaching for a smart pointer when a value or reference is enough.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 350,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.ownership_transfer",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Ownership transfer with std::move",
    description: "Transfer exclusive ownership of a unique_ptr with std::move and understand the moved-from state.",
    learner_goal: "Move a unique_ptr to hand off ownership and explain why the source becomes empty.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 360,
    is_active: true
  },
  {
    id: "cpp.stl.vector",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::vector",
    description: "Use a resizable array that owns and manages its elements.",
    learner_goal: "Add, access, and size a vector, and access elements safely with at().",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 410,
    is_active: true
  },
  {
    id: "cpp.stl.string",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::string",
    description: "Use a growable character sequence that manages its own memory.",
    learner_goal: "Build, size, index, and search strings without manual memory management.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 420,
    is_active: true
  },
  {
    id: "cpp.stl.map",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::map and unordered_map",
    description: "Store key-value pairs with unique keys; choose ordered vs hashed lookup.",
    learner_goal: "Insert, look up, and check keys without accidentally inserting via operator[].",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 430,
    is_active: true
  },
  {
    id: "cpp.stl.set",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::set and unordered_set",
    description: "Store unique elements and test membership efficiently.",
    learner_goal: "Use a set to deduplicate and to check membership.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 440,
    is_active: true
  },
  {
    id: "cpp.stl.algorithms",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Standard algorithms",
    description: "Use <algorithm> and <numeric> functions instead of hand-written loops.",
    learner_goal: "Reach for sort, find, count, accumulate, and min/max_element on iterator ranges.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 450,
    is_active: true
  },
  {
    id: "cpp.stl.iterators",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Iterators and range-based for",
    description: "Understand begin/end ranges and iterate with range-based for loops.",
    learner_goal: "Explain the half-open [begin, end) range and iterate without manual index bookkeeping.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 460,
    is_active: true
  },
  {
    id: "cpp.stl.adapters",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Container adapters",
    description: "Use stack (LIFO), queue (FIFO), and priority_queue (highest priority first).",
    learner_goal: "Pick the right adapter for LIFO, FIFO, or priority access.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 470,
    is_active: true
  },
  {
    id: "cpp.stl.lambdas",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Lambdas",
    description: "Write inline anonymous functions and capture surrounding variables.",
    learner_goal: "Pass a lambda to an algorithm and control what it captures.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 480,
    is_active: true
  },
  {
    id: "dsa.arrays.indexing",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Array indexing",
    description: "Access elements by zero-based index and avoid off-by-one and out-of-bounds errors.",
    learner_goal: "Identify the valid index range of a sequence and spot off-by-one mistakes.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1010,
    is_active: true
  },
  {
    id: "dsa.arrays.traversal",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Array traversal",
    description: "Iterate through arrays and vectors correctly, visiting each element once.",
    learner_goal: "Write a loop that visits every element exactly once without skipping or overrunning.",
    level: "beginner",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1020,
    is_active: true
  },
  {
    id: "dsa.arrays.two_pointers",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Two pointers and sliding window",
    description: "Use two indices to solve pair and window problems in linear time.",
    learner_goal: "Replace an O(n^2) double loop with a linear two-pointer or sliding-window scan.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1030,
    is_active: true
  },
  {
    id: "dsa.searching.binary_search",
    domain: "dsa",
    module_id: "dsa.searching",
    title: "Binary search",
    description: "Find a target in a sorted sequence by repeatedly halving the search range.",
    learner_goal: "Use binary search on sorted data and explain why sorting is required.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1110,
    is_active: true
  },
  {
    id: "dsa.sorting.comparator",
    domain: "dsa",
    module_id: "dsa.sorting",
    title: "Sorting with a comparator",
    description: "Sort by a custom order using a comparator function or lambda.",
    learner_goal: "Pass a comparator to std::sort to order by a custom key or direction.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1210,
    is_active: true
  },
  {
    id: "dsa.stacks.basic_stack",
    domain: "dsa",
    module_id: "dsa.stacks",
    title: "Stacks and queues for problems",
    description: "Recognize when LIFO (stack) or FIFO (queue) structure fits a problem.",
    learner_goal: "Choose a stack for nested/reversible problems and a queue for level-order processing.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1310,
    is_active: true
  },
  {
    id: "dsa.hashing.lookup",
    domain: "dsa",
    module_id: "dsa.hashing",
    title: "Hash maps and sets for lookup",
    description: "Use hashing for average O(1) membership, counting, and duplicate detection.",
    learner_goal: "Trade memory for speed with a hash map/set instead of repeated linear scans.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1410,
    is_active: true
  },
  {
    id: "dsa.recursion.base_case",
    domain: "dsa",
    module_id: "dsa.recursion",
    title: "Recursion and base cases",
    description: "Write a recursive function with a base case and a step toward it.",
    learner_goal: "Identify the base case and the recursive step, and avoid infinite recursion.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1510,
    is_active: true
  }
];

export const skillPrerequisitesSeed: SkillPrerequisite[] = [
  { skill_id: "cpp.program_basics.io", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.variables", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.conversions", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.conditionals", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.loops", prerequisite_skill_id: "cpp.control_flow.conditionals", relationship_type: "recommended" },
  { skill_id: "cpp.functions.basics", prerequisite_skill_id: "cpp.control_flow.loops", relationship_type: "recommended" },
  { skill_id: "cpp.functions.decomposition", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.syntax", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.references.references", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.references.pointers", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.const_correctness", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.parameter_passing", prerequisite_skill_id: "cpp.references.const_correctness", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.public_private", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.const_methods_intro", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.invariants_intro", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.default_constructor", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.parameterized_constructor", prerequisite_skill_id: "cpp.constructors.default_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.member_initializer_list", prerequisite_skill_id: "cpp.constructors.parameterized_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.destructor_intro", prerequisite_skill_id: "cpp.constructors.default_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.raii.resource_lifetime", prerequisite_skill_id: "cpp.constructors.destructor_intro", relationship_type: "recommended" },
  { skill_id: "cpp.raii.destructor_cleanup", prerequisite_skill_id: "cpp.raii.resource_lifetime", relationship_type: "recommended" },
  { skill_id: "cpp.raii.exception_safety_intro", prerequisite_skill_id: "cpp.raii.destructor_cleanup", relationship_type: "recommended" },
  { skill_id: "cpp.raii.ownership_boundary", prerequisite_skill_id: "cpp.raii.resource_lifetime", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.unique_ptr", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.shared_ptr", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.weak_ptr", prerequisite_skill_id: "cpp.smart_pointers.shared_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.cyclic_reference", prerequisite_skill_id: "cpp.smart_pointers.weak_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.ownership_choice", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.ownership_transfer", prerequisite_skill_id: "cpp.smart_pointers.unique_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.stl.vector", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.stl.string", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.map", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.set", prerequisite_skill_id: "cpp.stl.map", relationship_type: "recommended" },
  { skill_id: "cpp.stl.iterators", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.algorithms", prerequisite_skill_id: "cpp.stl.iterators", relationship_type: "recommended" },
  { skill_id: "cpp.stl.adapters", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.lambdas", prerequisite_skill_id: "cpp.stl.algorithms", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.indexing", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.traversal", prerequisite_skill_id: "dsa.arrays.indexing", relationship_type: "recommended" },
  { skill_id: "dsa.sorting.comparator", prerequisite_skill_id: "cpp.stl.algorithms", relationship_type: "recommended" },
  { skill_id: "dsa.searching.binary_search", prerequisite_skill_id: "dsa.sorting.comparator", relationship_type: "recommended" },
  { skill_id: "dsa.stacks.basic_stack", prerequisite_skill_id: "cpp.stl.adapters", relationship_type: "recommended" },
  { skill_id: "dsa.hashing.lookup", prerequisite_skill_id: "cpp.stl.map", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.two_pointers", prerequisite_skill_id: "dsa.arrays.traversal", relationship_type: "recommended" },
  { skill_id: "dsa.recursion.base_case", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" }
];

export function getSeedSkillMapPreview(): SkillMapPreviewData {
  return {
    modules: [...skillModules].sort((a, b) => a.order_index - b.order_index),
    skills: skillSeed,
    prerequisites: skillPrerequisitesSeed,
    source: "seed"
  };
}

export function getSkillsForModule(moduleId: string, skills = skillSeed) {
  return skills
    .filter((skill) => skill.module_id === moduleId && skill.is_active)
    .sort((a, b) => a.order_index - b.order_index);
}
