import type { Skill, SkillMapPreviewData, SkillModule, SkillPrerequisite } from "./skill-types";

/*
 * This seed mirrors supabase/migrations/20260612011000_create_skill_map.sql.
 * It is the source of truth for the read-only dashboard preview when the
 * Supabase skill migration has not been applied yet, and it keeps stable
 * skill ids aligned with docs/SKILL_ENGINE.md.
 *
 * Keep this file and the SQL migration in lockstep: the seed-integrity unit
 * tests guard structure, but the two must agree on ids, modules, and order.
 */

export const skillModules: SkillModule[] = [
  { id: "cpp.program_basics", title: "Program basics", description: "Program structure and console I/O.", order_index: 2 },
  { id: "cpp.values_types", title: "Values and types", description: "Variables, types, and conversions.", order_index: 4 },
  { id: "cpp.control_flow", title: "Control flow", description: "Conditionals and loops.", order_index: 6 },
  { id: "cpp.functions", title: "Functions", description: "Declarations, parameters, and decomposition.", order_index: 8 },
  { id: "cpp.references", title: "References, pointers, and const", description: "Aliases, addresses, const-correctness, and parameter passing.", order_index: 9 },
  { id: "cpp.structs_classes", title: "Structs and classes", description: "Members and access control.", order_index: 10 },
  { id: "cpp.constructors", title: "Constructors", description: "Object initialization and lifetime.", order_index: 20 },
  { id: "cpp.value_semantics", title: "Value semantics", description: "Copy, move, and the Rule of Zero/Five.", order_index: 25 },
  { id: "cpp.oop", title: "Object-oriented design", description: "Composition, inheritance, and runtime polymorphism.", order_index: 26 },
  { id: "cpp.raii", title: "RAII", description: "Resource ownership and cleanup.", order_index: 30 },
  { id: "cpp.smart_pointers", title: "Smart pointers", description: "Modern ownership helpers.", order_index: 40 },
  { id: "cpp.stl", title: "STL containers", description: "Everyday standard-library containers.", order_index: 50 },
  { id: "cpp.templates", title: "Templates and generics", description: "Function/class templates, concepts, and ranges.", order_index: 60 },
  { id: "cpp.tooling", title: "Testing, debugging, and tooling", description: "Error handling, tests, debugging, and builds.", order_index: 70 },
  { id: "cpp.concurrency", title: "Concurrency", description: "Threads, data races, mutexes, and async tasks.", order_index: 75 },
  { id: "cpp.utilities", title: "Utility libraries", description: "File I/O, filesystem, time, randomness, and variant types.", order_index: 76 },
  { id: "dsa.complexity", title: "Complexity and problem solving", description: "Big-O and a systematic solving process.", order_index: 105 },
  { id: "dsa.arrays", title: "Arrays and sequences", description: "Indexing and traversal fundamentals.", order_index: 110 },
  { id: "dsa.searching", title: "Searching", description: "Finding values efficiently.", order_index: 120 },
  { id: "dsa.sorting", title: "Sorting", description: "Ordering with comparators.", order_index: 130 },
  { id: "dsa.stacks", title: "Stacks and queues", description: "LIFO and FIFO problem patterns.", order_index: 140 },
  { id: "dsa.hashing", title: "Hashing", description: "Hash maps and sets for fast lookup.", order_index: 150 },
  { id: "dsa.trees", title: "Trees, heaps, and DSU", description: "Tree traversal, heaps, and union-find.", order_index: 160 },
  { id: "dsa.recursion", title: "Recursion", description: "Base cases and recursive structure.", order_index: 155 },
  { id: "dsa.graphs", title: "Graphs", description: "Graph representation, traversal, and shortest paths.", order_index: 170 },
  { id: "dsa.techniques", title: "Algorithmic techniques", description: "Prefix sums, sliding window, greedy, and dynamic programming.", order_index: 180 },
  { id: "dsa.strings", title: "String algorithms", description: "String manipulation, searching, palindromes, and parsing.", order_index: 190 },
  { id: "dsa.math", title: "Math for programming", description: "Bit manipulation, number theory, combinatorics, and geometry.", order_index: 200 }
];

export const skillSeed: Skill[] = [
  {
    id: "cpp.program_basics.structure",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Program structure and main()",
    description: "Read a minimal program: includes, main(), statements, and return values.",
    learner_goal: "Explain where a program starts and what main()'s return value means.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 1,
    is_active: true
  },
  {
    id: "cpp.program_basics.io",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Console input and output",
    description: "Print with std::cout and read with std::cin.",
    learner_goal: "Write output and read input using the iostream operators.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 2,
    is_active: true
  },
  {
    id: "cpp.program_basics.statements_comments",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Statements, comments, and naming",
    description: "Terminate statements, write comments, and follow common naming conventions.",
    learner_goal: "Write well-formed statements with clear comments and conventional names.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 3,
    is_active: true
  },
  {
    id: "cpp.program_basics.exit_status",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "main() return value and exit status",
    description: "Understand what main()'s return value means as the program's exit status.",
    learner_goal: "Explain that returning 0 from main() signals success to the operating system.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 4,
    is_active: true
  },
  {
    id: "cpp.program_basics.error_kinds",
    domain: "cpp",
    module_id: "cpp.program_basics",
    title: "Compile-time, link-time, and run-time errors",
    description: "Tell apart errors caught by the compiler, the linker, and at run time.",
    learner_goal: "Classify a failure as a compile-time, link-time, or run-time error.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 5,
    is_active: true
  },
  {
    id: "cpp.values_types.variables",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Variables, types, and initialization",
    description: "Declare and initialize variables of the fundamental types.",
    learner_goal: "Choose a fundamental type, initialize on declaration, and use auto/const.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 3,
    is_active: true
  },
  {
    id: "cpp.values_types.conversions",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Conversions and casts",
    description: "Understand truncation, narrowing, and static_cast.",
    learner_goal: "Predict the result of a numeric conversion and cast explicitly with static_cast.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 4,
    is_active: true
  },
  {
    id: "cpp.values_types.fundamental_types",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Choosing a fundamental type",
    description: "Pick among integers, floating point, bool, and char by range and intent.",
    learner_goal: "Choose int/double/bool/char appropriately and know integers are exact while doubles are approximate.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 5,
    is_active: true
  },
  {
    id: "cpp.values_types.signed_unsigned",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Signed and unsigned pitfalls",
    description: "Avoid bugs from mixing signed and unsigned integers and from unsigned wraparound.",
    learner_goal: "Spot signed/unsigned comparison and wraparound bugs, e.g. with container .size().",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 6,
    is_active: true
  },
  {
    id: "cpp.values_types.literals",
    domain: "cpp",
    module_id: "cpp.values_types",
    title: "Literals and expression evaluation",
    description: "Read literals and evaluate expressions, including integer division.",
    learner_goal: "Predict an expression's value, including integer division and operator precedence.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 7,
    is_active: true
  },
  {
    id: "cpp.control_flow.conditionals",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Conditionals",
    description: "Branch with if/else and switch using comparison and logical operators.",
    learner_goal: "Write correct if/else and switch logic and avoid switch fall-through.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 5,
    is_active: true
  },
  {
    id: "cpp.control_flow.loops",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Loops",
    description: "Repeat with for/while and control flow with break/continue.",
    learner_goal: "Write a loop that runs the right number of times and avoid off-by-one errors.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 6,
    is_active: true
  },
  {
    id: "cpp.control_flow.logical_operators",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Logical operators and compound conditions",
    description: "Combine conditions with &&, ||, and ! and rely on short-circuit evaluation.",
    learner_goal: "Build compound conditions and use short-circuiting to guard later operands.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 7,
    is_active: true
  },
  {
    id: "cpp.control_flow.switch_statement",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "switch and break",
    description: "Branch on a value with switch, and understand break and fallthrough.",
    learner_goal: "Write a switch with break per case and know what happens without break.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 8,
    is_active: true
  },
  {
    id: "cpp.control_flow.loop_invariants",
    domain: "cpp",
    module_id: "cpp.control_flow",
    title: "Loop invariants and off-by-one",
    description: "Reason about what stays true each iteration and pick correct loop bounds.",
    learner_goal: "State a loop invariant and choose bounds that avoid off-by-one errors.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 9,
    is_active: true
  },
  {
    id: "cpp.functions.basics",
    domain: "cpp",
    module_id: "cpp.functions",
    title: "Function basics",
    description: "Declare functions with parameters, return values, and local scope.",
    learner_goal: "Write and call a function, and explain where its local variables live.",
    level: "beginner",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 7,
    is_active: true
  },
  {
    id: "cpp.functions.decomposition",
    domain: "cpp",
    module_id: "cpp.functions",
    title: "Decomposition and headers",
    description: "Split work into small functions and across header/source files.",
    learner_goal: "Break a task into small, well-named functions and place declarations in a header.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 8,
    is_active: true
  },
  {
    id: "cpp.references.references",
    domain: "cpp",
    module_id: "cpp.references",
    title: "References",
    description: "Use lvalue references as aliases for existing objects.",
    learner_goal: "Bind a reference and use it to modify the caller's object.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 90,
    is_active: true
  },
  {
    id: "cpp.references.pointers",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Pointers and nullptr",
    description: "Hold addresses, dereference safely, and handle nullptr.",
    learner_goal: "Take an address, dereference a pointer, and avoid null dereferences.",
    level: "beginner",
    item_types: ["lesson", "quiz"],
    order_index: 91,
    is_active: true
  },
  {
    id: "cpp.references.const_correctness",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Const correctness",
    description: "Use const to express and enforce read-only intent.",
    learner_goal: "Apply const to parameters and methods to prevent accidental modification.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 92,
    is_active: true
  },
  {
    id: "cpp.references.parameter_passing",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Parameter passing",
    description: "Choose by-value, const-reference, or reference for parameters.",
    learner_goal: "Pass small types by value, large read-only types by const reference, and outputs by reference.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 93,
    is_active: true
  },
  {
    id: "cpp.references.lvalue_rvalue",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Lvalues and rvalues",
    description: "Tell apart named objects (lvalues) and temporaries (rvalues).",
    learner_goal: "Decide whether an expression is an lvalue or an rvalue and why it matters for binding.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 94,
    is_active: true
  },
  {
    id: "cpp.references.return_semantics",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Return by value vs by reference",
    description: "Choose between returning a value and returning a reference safely.",
    learner_goal: "Return by value by default; return a reference only to storage that outlives the call.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 95,
    is_active: true
  },
  {
    id: "cpp.references.dangling",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Dangling references and lifetimes",
    description: "Spot references that outlive their referent and the limits of lifetime extension.",
    learner_goal: "Identify a dangling reference and know that lifetime extension does not survive a return.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 96,
    is_active: true
  },
  {
    id: "cpp.references.pointer_const",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Pointer-to-const vs const pointer",
    description: "Tell apart a pointer to const data and a const pointer to mutable data.",
    learner_goal: "Read const placement to know whether the pointee or the pointer itself is const.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 97,
    is_active: true
  },
  {
    id: "cpp.references.non_owning",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Non-owning pointers and selection",
    description: "Use raw pointers only as non-owning observers and choose pointer vs reference.",
    learner_goal: "Treat a raw pointer as a non-owning, nullable observer and pick reference when non-null.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 98,
    is_active: true
  },
  {
    id: "cpp.references.views",
    domain: "cpp",
    module_id: "cpp.references",
    title: "Non-owning views: span and string_view",
    description: "Pass arrays/strings as std::span / std::string_view without unsafe pointer arithmetic.",
    learner_goal: "Use a view to borrow a range safely instead of pointer+length and raw arithmetic.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 99,
    is_active: true
  },
  {
    id: "cpp.structs_classes.syntax",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Struct/class syntax",
    description: "Define simple structs and classes with member fields and methods.",
    learner_goal: "Write a small type and explain how objects are created from it.",
    level: "beginner",
    item_types: ["lesson", "fill_blank", "code_reading"],
    order_index: 10,
    is_active: true
  },
  {
    id: "cpp.structs_classes.public_private",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Public and private access",
    description: "Use access control to protect object state and understand compiler access errors.",
    learner_goal: "Decide which members should be public or private and fix simple access mistakes.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting", "code_reading"],
    order_index: 20,
    is_active: true
  },
  {
    id: "cpp.structs_classes.const_methods_intro",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Const methods intro",
    description: "Read const method declarations and understand why const objects need const-safe methods.",
    learner_goal: "Predict whether a method call on a const object should compile.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting"],
    order_index: 30,
    is_active: true
  },
  {
    id: "cpp.structs_classes.invariants_intro",
    domain: "cpp",
    module_id: "cpp.structs_classes",
    title: "Class invariants intro",
    description: "Explain how classes maintain valid state through constructors and member functions.",
    learner_goal: "Describe the rule that must stay true for an object after every public method.",
    level: "beginner",
    item_types: ["lesson", "concept_check"],
    order_index: 40,
    is_active: true
  },
  {
    id: "cpp.constructors.default_constructor",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Default constructor",
    description: "Explain and write a constructor with no arguments.",
    learner_goal: "Create an object with safe default state.",
    level: "beginner",
    item_types: ["lesson", "fill_blank"],
    order_index: 110,
    is_active: true
  },
  {
    id: "cpp.constructors.parameterized_constructor",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Parameterized constructor",
    description: "Initialize object state through constructor arguments.",
    learner_goal: "Use constructor parameters to make invalid states harder to create.",
    level: "beginner",
    item_types: ["lesson", "code_reading"],
    order_index: 120,
    is_active: true
  },
  {
    id: "cpp.constructors.member_initializer_list",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Member initializer list",
    description: "Use initializer lists and explain why they are preferred for direct initialization.",
    learner_goal: "Choose an initializer list over assignment inside the constructor body.",
    level: "beginner",
    item_types: ["quiz", "bug_spotting"],
    order_index: 130,
    is_active: true
  },
  {
    id: "cpp.constructors.destructor_intro",
    domain: "cpp",
    module_id: "cpp.constructors",
    title: "Destructor intro",
    description: "Explain when destructors run and why they matter for resources.",
    learner_goal: "Predict the lifetime order of simple stack objects.",
    level: "beginner",
    item_types: ["lesson", "predict_output"],
    order_index: 140,
    is_active: true
  },
  {
    id: "cpp.value_semantics.copy",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Copy semantics",
    description: "Understand copy constructor/assignment and deep vs shallow copies.",
    learner_goal: "Explain why a class owning a raw resource needs a deep copy.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 251,
    is_active: true
  },
  {
    id: "cpp.value_semantics.move",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Move semantics",
    description: "Transfer resources with move constructor/assignment and std::move.",
    learner_goal: "Explain how a move steals resources and leaves the source valid but empty.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 252,
    is_active: true
  },
  {
    id: "cpp.value_semantics.rule_of_zero_five",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Rule of Zero and Rule of Five",
    description: "Prefer self-managing members; if you write one special member, write all five.",
    learner_goal: "Apply the Rule of Zero and recognize when the Rule of Five applies.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 253,
    is_active: true
  },
  {
    id: "cpp.value_semantics.special_members",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Which special member runs",
    description: "Tell apart copy/move construction and assignment, and control them with =default/=delete.",
    learner_goal: "Predict which special member a statement invokes and know moved-from objects are valid but unspecified.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 254,
    is_active: true
  },
  {
    id: "cpp.value_semantics.copy_elision",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Copy elision and return by value",
    description: "Reason about why returning by value is cheap and when deep vs shallow copies matter.",
    learner_goal: "Explain copy elision so returning a local by value is efficient, not a costly copy.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 255,
    is_active: true
  },
  {
    id: "cpp.value_semantics.operators",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Operator overloading and conversions",
    description: "Design equality/ordering and conversions that behave the way callers expect.",
    learner_goal: "Give operators their conventional meaning and use explicit to avoid surprising conversions.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 256,
    is_active: true
  },
  {
    id: "cpp.value_semantics.self_assignment",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Self-assignment safety",
    description: "Write assignment that stays correct when an object is assigned to itself.",
    learner_goal: "Make a hand-written assignment self-assignment safe (guard or copy-and-swap).",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 257,
    is_active: true
  },
  {
    id: "cpp.value_semantics.deep_copy",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Shallow vs deep copy",
    description: "Spot a shallow copy of an owned pointer that leads to double free or shared state.",
    learner_goal: "Recognize a shallow-copy bug and fix it with a deep copy or self-managing member.",
    level: "advanced",
    item_types: ["lesson", "bug_spotting"],
    order_index: 258,
    is_active: true
  },
  {
    id: "cpp.value_semantics.stream_insertion",
    domain: "cpp",
    module_id: "cpp.value_semantics",
    title: "Stream insertion (operator<<)",
    description: "Print a type by overloading operator<< as a non-member taking std::ostream&.",
    learner_goal: "Define operator<<(std::ostream&, const T&) to make a type printable.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 259,
    is_active: true
  },
  {
    id: "cpp.oop.composition",
    domain: "cpp",
    module_id: "cpp.oop",
    title: "Composition",
    description: "Model has-a relationships by holding objects as members.",
    learner_goal: "Prefer composition for has-a relationships and reuse without inheritance.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 260,
    is_active: true
  },
  {
    id: "cpp.oop.inheritance",
    domain: "cpp",
    module_id: "cpp.oop",
    title: "Inheritance",
    description: "Model is-a relationships by deriving a class from a base.",
    learner_goal: "Use public inheritance for is-a relationships and access inherited members.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 261,
    is_active: true
  },
  {
    id: "cpp.oop.virtual_polymorphism",
    domain: "cpp",
    module_id: "cpp.oop",
    title: "Virtual functions and polymorphism",
    description: "Call derived behavior through a base pointer with virtual functions.",
    learner_goal: "Use virtual functions for runtime dispatch and a virtual destructor on base classes.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 262,
    is_active: true
  },
  {
    id: "cpp.oop.abstract_interfaces",
    domain: "cpp",
    module_id: "cpp.oop",
    title: "Abstract classes and interfaces",
    description: "Define interfaces with pure virtual functions that derived classes implement.",
    learner_goal: "Declare a pure virtual function to create an interface other classes implement.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 263,
    is_active: true
  },
  {
    id: "cpp.raii.resource_lifetime",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Resource lifetime",
    description: "Connect resource acquisition to object lifetime.",
    learner_goal: "Explain why the object that owns a resource should release it automatically.",
    level: "intermediate",
    item_types: ["lesson", "concept_check"],
    order_index: 210,
    is_active: true
  },
  {
    id: "cpp.raii.destructor_cleanup",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Destructor cleanup",
    description: "Use destructors to release resources when ownership is manual.",
    learner_goal: "Read a wrapper type and identify the cleanup point.",
    level: "intermediate",
    item_types: ["lesson", "code_reading"],
    order_index: 220,
    is_active: true
  },
  {
    id: "cpp.raii.exception_safety_intro",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Exception safety intro",
    description: "Explain why RAII helps when code exits early because of return or exception.",
    learner_goal: "Recognize why cleanup should not depend on reaching the last line of a function.",
    level: "intermediate",
    item_types: ["quiz", "code_reading"],
    order_index: 230,
    is_active: true
  },
  {
    id: "cpp.raii.ownership_boundary",
    domain: "cpp",
    module_id: "cpp.raii",
    title: "Ownership boundary",
    description: "Identify which object owns a resource and which code only observes it.",
    learner_goal: "Draw the boundary between owner and non-owner in small examples.",
    level: "intermediate",
    item_types: ["quiz", "bug_spotting"],
    order_index: 240,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.unique_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "unique_ptr",
    description: "Use unique ownership and explain why unique_ptr cannot be copied.",
    learner_goal: "Transfer ownership with move and avoid accidental shared ownership.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 310,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.shared_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "shared_ptr",
    description: "Explain shared ownership and reference counting at a beginner-friendly level.",
    learner_goal: "Identify when multiple objects intentionally share ownership.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 320,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.weak_ptr",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "weak_ptr",
    description: "Explain non-owning observation and cyclic-reference prevention.",
    learner_goal: "Recognize when a pointer should observe without extending lifetime.",
    level: "intermediate",
    item_types: ["lesson", "code_reading"],
    order_index: 330,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.cyclic_reference",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Cyclic references",
    description: "Spot a shared_ptr cycle and explain why it leaks.",
    learner_goal: "Break a cycle by changing one side to weak_ptr.",
    level: "intermediate",
    item_types: ["bug_spotting", "code_reading"],
    order_index: 340,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.ownership_choice",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Choosing the right ownership",
    description: "Decide between a stack object, a value member, a non-owning reference, and a smart pointer.",
    learner_goal: "Pick the simplest ownership that works, and avoid reaching for a smart pointer when a value or reference is enough.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 350,
    is_active: true
  },
  {
    id: "cpp.smart_pointers.ownership_transfer",
    domain: "cpp",
    module_id: "cpp.smart_pointers",
    title: "Ownership transfer with std::move",
    description: "Transfer exclusive ownership of a unique_ptr with std::move and understand the moved-from state.",
    learner_goal: "Move a unique_ptr to hand off ownership and explain why the source becomes empty.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 360,
    is_active: true
  },
  {
    id: "cpp.stl.vector",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::vector",
    description: "Use a resizable array that owns and manages its elements.",
    learner_goal: "Add, access, and size a vector, and access elements safely with at().",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 410,
    is_active: true
  },
  {
    id: "cpp.stl.string",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::string",
    description: "Use a growable character sequence that manages its own memory.",
    learner_goal: "Build, size, index, and search strings without manual memory management.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 420,
    is_active: true
  },
  {
    id: "cpp.stl.map",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::map and unordered_map",
    description: "Store key-value pairs with unique keys; choose ordered vs hashed lookup.",
    learner_goal: "Insert, look up, and check keys without accidentally inserting via operator[].",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 430,
    is_active: true
  },
  {
    id: "cpp.stl.set",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "std::set and unordered_set",
    description: "Store unique elements and test membership efficiently.",
    learner_goal: "Use a set to deduplicate and to check membership.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 440,
    is_active: true
  },
  {
    id: "cpp.stl.algorithms",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Standard algorithms",
    description: "Use <algorithm> and <numeric> functions instead of hand-written loops.",
    learner_goal: "Reach for sort, find, count, accumulate, and min/max_element on iterator ranges.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 450,
    is_active: true
  },
  {
    id: "cpp.stl.iterators",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Iterators and range-based for",
    description: "Understand begin/end ranges and iterate with range-based for loops.",
    learner_goal: "Explain the half-open [begin, end) range and iterate without manual index bookkeeping.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 460,
    is_active: true
  },
  {
    id: "cpp.stl.adapters",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Container adapters",
    description: "Use stack (LIFO), queue (FIFO), and priority_queue (highest priority first).",
    learner_goal: "Pick the right adapter for LIFO, FIFO, or priority access.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 470,
    is_active: true
  },
  {
    id: "cpp.stl.lambdas",
    domain: "cpp",
    module_id: "cpp.stl",
    title: "Lambdas",
    description: "Write inline anonymous functions and capture surrounding variables.",
    learner_goal: "Pass a lambda to an algorithm and control what it captures.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 480,
    is_active: true
  },
  {
    id: "cpp.templates.function_templates",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Function templates",
    description: "Write one function that works for many types via template type deduction.",
    learner_goal: "Define and call a function template and explain how T is deduced.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 601,
    is_active: true
  },
  {
    id: "cpp.templates.class_templates",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Class templates",
    description: "Parameterize a class by type, like the standard containers.",
    learner_goal: "Define and instantiate a simple class template.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 602,
    is_active: true
  },
  {
    id: "cpp.templates.concepts",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Concepts",
    description: "Constrain template parameters with C++20 concepts for clearer intent and errors.",
    learner_goal: "Constrain a template parameter to types that satisfy a requirement.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 603,
    is_active: true
  },
  {
    id: "cpp.templates.ranges",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Ranges and views",
    description: "Operate on whole ranges and compose lazy views (C++20).",
    learner_goal: "Use a range algorithm and a composed view without manual iterators.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 604,
    is_active: true
  },
  {
    id: "cpp.templates.constexpr",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "constexpr functions and values",
    description: "Evaluate functions and values at compile time with constexpr.",
    learner_goal: "Write a constexpr function and know when it runs at compile time vs run time.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 605,
    is_active: true
  },
  {
    id: "cpp.templates.if_constexpr",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "if constexpr",
    description: "Select a branch at compile time so the discarded branch is not instantiated.",
    learner_goal: "Use if constexpr to pick code per type without invalid branches being compiled.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 606,
    is_active: true
  },
  {
    id: "cpp.templates.static_assert",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "static_assert",
    description: "Enforce compile-time invariants with a clear message.",
    learner_goal: "Add a static_assert that fails the build with a readable message when an assumption breaks.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 607,
    is_active: true
  },
  {
    id: "cpp.templates.multiple_params",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Multiple and non-type template parameters",
    description: "Use several type parameters and compile-time value (non-type) parameters.",
    learner_goal: "Write templates with multiple type params and a non-type param like std::size_t N.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 608,
    is_active: true
  },
  {
    id: "cpp.templates.deduction",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Type deduction and instantiation",
    description: "Reason about template argument deduction and why templates live in headers.",
    learner_goal: "Predict deduced template arguments and explain header-only instantiation/linkage.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 609,
    is_active: true
  },
  {
    id: "cpp.templates.aliases_specialization",
    domain: "cpp",
    module_id: "cpp.templates",
    title: "Alias templates and specialization",
    description: "Name types with using/alias templates and introduce template specialization.",
    learner_goal: "Define an alias template and recognize when a specialization customizes behavior.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 610,
    is_active: true
  },
  {
    id: "cpp.tooling.error_handling",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Error handling",
    description: "Use exceptions and error returns to signal and handle failures.",
    learner_goal: "Throw and catch exceptions and choose between exceptions and error returns.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 701,
    is_active: true
  },
  {
    id: "cpp.tooling.testing",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Testing",
    description: "Write unit tests and assertions to verify behavior.",
    learner_goal: "Write a small unit test that fails before a fix and passes after.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 702,
    is_active: true
  },
  {
    id: "cpp.tooling.debugging",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Debugging",
    description: "Locate bugs with a debugger, breakpoints, and targeted output.",
    learner_goal: "Use a debugger and a minimal reproduction to isolate a bug.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 703,
    is_active: true
  },
  {
    id: "cpp.tooling.build",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Compiling and building",
    description: "Understand compile vs link and the role of a build system.",
    learner_goal: "Explain the compile/link stages and what a build system automates.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 704,
    is_active: true
  },
  {
    id: "cpp.tooling.warnings",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Warnings and warnings-as-errors",
    description: "Enable strong warnings and treat them as build-failing signals.",
    learner_goal: "Build with -Wall -Wextra and explain why -Werror keeps warnings from piling up.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 705,
    is_active: true
  },
  {
    id: "cpp.tooling.sanitizers",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Address and UB sanitizers",
    description: "Catch memory and undefined-behavior bugs at run time with ASan/UBSan.",
    learner_goal: "Build with -fsanitize=address,undefined to surface UB and memory errors in tests.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 706,
    is_active: true
  },
  {
    id: "cpp.tooling.cmake",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "CMake builds",
    description: "Define targets and link dependencies; choose Debug vs Release.",
    learner_goal: "Read a small CMakeLists with a target plus includes/links and pick a build type.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 707,
    is_active: true
  },
  {
    id: "cpp.tooling.preconditions",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Preconditions and input validation",
    description: "Validate untrusted input at boundaries and assert internal preconditions.",
    learner_goal: "Validate external input but assert (not validate) caller contracts you control.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 708,
    is_active: true
  },
  {
    id: "cpp.tooling.optional_expected",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Signaling failure with optional and expected",
    description: "Return std::optional for absence and std::expected for a recoverable error value.",
    learner_goal: "Choose std::optional for a maybe-value and std::expected to carry an error reason.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 709,
    is_active: true
  },
  {
    id: "cpp.tooling.error_strategy",
    domain: "cpp",
    module_id: "cpp.tooling",
    title: "Choosing an error-handling strategy",
    description: "Pick exceptions, error codes, or optional/expected, and avoid exceptions for control flow.",
    learner_goal: "Select an error mechanism by recoverability and frequency; reserve exceptions for the exceptional.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 710,
    is_active: true
  },
  {
    id: "cpp.concurrency.threads",
    domain: "cpp",
    module_id: "cpp.concurrency",
    title: "Threads",
    description: "Run work concurrently with std::thread and join or detach it.",
    learner_goal: "Start a std::thread and join it before its work is needed or the program ends.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 750,
    is_active: true
  },
  {
    id: "cpp.concurrency.data_races",
    domain: "cpp",
    module_id: "cpp.concurrency",
    title: "Data races",
    description: "Recognize undefined behavior from unsynchronized shared mutable state.",
    learner_goal: "Identify a data race: concurrent access to shared data with at least one writer.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 751,
    is_active: true
  },
  {
    id: "cpp.concurrency.mutexes",
    domain: "cpp",
    module_id: "cpp.concurrency",
    title: "Mutexes and locks",
    description: "Protect shared data with std::mutex and RAII lock guards.",
    learner_goal: "Use std::lock_guard to hold a mutex for the duration of a critical section.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 752,
    is_active: true
  },
  {
    id: "cpp.concurrency.async",
    domain: "cpp",
    module_id: "cpp.concurrency",
    title: "Async tasks and futures",
    description: "Run a task with std::async and collect its result through a future.",
    learner_goal: "Launch work with std::async and retrieve the result via future::get.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 753,
    is_active: true
  },
  {
    id: "cpp.utilities.file_io",
    domain: "cpp",
    module_id: "cpp.utilities",
    title: "File I/O and filesystem",
    description: "Read and write files with fstream and inspect paths with std::filesystem.",
    learner_goal: "Open a file with ofstream/ifstream and check existence with std::filesystem.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 760,
    is_active: true
  },
  {
    id: "cpp.utilities.chrono",
    domain: "cpp",
    module_id: "cpp.utilities",
    title: "Time with chrono",
    description: "Measure durations and elapsed time with std::chrono clocks.",
    learner_goal: "Time a code block with steady_clock and convert the duration to milliseconds.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 761,
    is_active: true
  },
  {
    id: "cpp.utilities.random",
    domain: "cpp",
    module_id: "cpp.utilities",
    title: "Random numbers",
    description: "Generate quality random values with <random> engines and distributions.",
    learner_goal: "Use a random engine plus a distribution instead of rand() % n.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 762,
    is_active: true
  },
  {
    id: "cpp.utilities.variant",
    domain: "cpp",
    module_id: "cpp.utilities",
    title: "Variant and optional",
    description: "Model alternatives with std::variant and maybe-values with std::optional.",
    learner_goal: "Use std::optional for a maybe-value and std::variant for a type-safe union.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 763,
    is_active: true
  },
  {
    id: "dsa.complexity.big_o",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Big-O notation",
    description: "Describe how running time grows with input size, ignoring constants.",
    learner_goal: "Name the Big-O of common loops and pick the dominant term.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1005,
    is_active: true
  },
  {
    id: "dsa.complexity.problem_solving",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Systematic problem solving",
    description: "Work from understanding to brute force to an optimized, tested solution.",
    learner_goal: "Follow a repeatable process: understand, example, brute force, optimize, test.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1006,
    is_active: true
  },
  {
    id: "dsa.complexity.growth_rates",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Comparing growth rates",
    description: "Order common complexities and count the dominant operations in a loop.",
    learner_goal: "Rank O(1), O(log n), O(n), O(n log n), O(n^2), and exponential, and find the dominant term.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1007,
    is_active: true
  },
  {
    id: "dsa.complexity.amortized",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Amortized analysis",
    description: "Reason about average cost per operation across a sequence, like vector::push_back.",
    learner_goal: "Explain why vector::push_back is amortized O(1) despite occasional resizes.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1008,
    is_active: true
  },
  {
    id: "dsa.complexity.constraints",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Reading input constraints",
    description: "Use input size limits to infer a feasible target complexity and spot hidden costs.",
    learner_goal: "Reject infeasible approaches from input bounds and detect hidden nested-loop cost.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1009,
    is_active: true
  },
  {
    id: "dsa.complexity.pattern_recognition",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Recognizing the right pattern",
    description: "Map common problem cues to a frequency map, two-pointer/window, prefix, or sort-then-scan approach.",
    learner_goal: "Read a problem's cues and pick the standard pattern that fits before coding.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1010,
    is_active: true
  },
  {
    id: "dsa.complexity.container_selection",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Choosing a container from operations",
    description: "Pick vector/map/unordered_map/set/stack/queue/priority_queue from the operations a task needs.",
    learner_goal: "Choose a container by the operations and complexity a problem requires.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1011,
    is_active: true
  },
  {
    id: "dsa.complexity.recursion_choice",
    domain: "dsa",
    module_id: "dsa.complexity",
    title: "Recursion, iteration, and backtracking",
    description: "Decide when recursion or backtracking fits versus a plain iterative loop.",
    learner_goal: "Recognize recursive/backtracking structure and when iteration is simpler.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1012,
    is_active: true
  },
  {
    id: "dsa.arrays.indexing",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Array indexing",
    description: "Access elements by zero-based index and avoid off-by-one and out-of-bounds errors.",
    learner_goal: "Identify the valid index range of a sequence and spot off-by-one mistakes.",
    level: "beginner",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1010,
    is_active: true
  },
  {
    id: "dsa.arrays.traversal",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Array traversal",
    description: "Iterate through arrays and vectors correctly, visiting each element once.",
    learner_goal: "Write a loop that visits every element exactly once without skipping or overrunning.",
    level: "beginner",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1020,
    is_active: true
  },
  {
    id: "dsa.arrays.two_pointers",
    domain: "dsa",
    module_id: "dsa.arrays",
    title: "Two pointers and sliding window",
    description: "Use two indices to solve pair and window problems in linear time.",
    learner_goal: "Replace an O(n^2) double loop with a linear two-pointer or sliding-window scan.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1030,
    is_active: true
  },
  {
    id: "dsa.searching.binary_search",
    domain: "dsa",
    module_id: "dsa.searching",
    title: "Binary search",
    description: "Find a target in a sorted sequence by repeatedly halving the search range.",
    learner_goal: "Use binary search on sorted data and explain why sorting is required.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1110,
    is_active: true
  },
  {
    id: "dsa.sorting.comparator",
    domain: "dsa",
    module_id: "dsa.sorting",
    title: "Sorting with a comparator",
    description: "Sort by a custom order using a comparator function or lambda.",
    learner_goal: "Pass a comparator to std::sort to order by a custom key or direction.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1210,
    is_active: true
  },
  {
    id: "dsa.stacks.basic_stack",
    domain: "dsa",
    module_id: "dsa.stacks",
    title: "Stacks and queues for problems",
    description: "Recognize when LIFO (stack) or FIFO (queue) structure fits a problem.",
    learner_goal: "Choose a stack for nested/reversible problems and a queue for level-order processing.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1310,
    is_active: true
  },
  {
    id: "dsa.hashing.lookup",
    domain: "dsa",
    module_id: "dsa.hashing",
    title: "Hash maps and sets for lookup",
    description: "Use hashing for average O(1) membership, counting, and duplicate detection.",
    learner_goal: "Trade memory for speed with a hash map/set instead of repeated linear scans.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "code_reading"],
    order_index: 1410,
    is_active: true
  },
  {
    id: "dsa.trees.linked_list",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Singly linked lists",
    description: "Model nodes that point to the next, and traverse/insert/delete safely.",
    learner_goal: "Traverse a singly linked list and insert/delete a node without leaking or dangling.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1600,
    is_active: true
  },
  {
    id: "dsa.trees.list_vs_vector",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "List vs vector tradeoffs",
    description: "Weigh memory locality against mid-sequence insertion when choosing a container.",
    learner_goal: "Explain why std::vector is the default and when a linked list actually helps.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1601,
    is_active: true
  },
  {
    id: "dsa.trees.tree_terminology",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Tree terminology and shape",
    description: "Name parts of a tree and reason about its recursive structure, height, and depth.",
    learner_goal: "Use root/leaf/subtree/height/depth correctly and see a tree as a recursive structure.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1605,
    is_active: true
  },
  {
    id: "dsa.trees.traversal",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Binary tree traversal",
    description: "Visit tree nodes in preorder, inorder, postorder, or level order.",
    learner_goal: "Choose the traversal that fits a task and know inorder sorts a BST.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1610,
    is_active: true
  },
  {
    id: "dsa.trees.heap",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Heaps and priority queues",
    description: "Use a binary heap for O(1) min/max access and O(log n) updates.",
    learner_goal: "Recognize when a heap (priority_queue) is the right tool.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1620,
    is_active: true
  },
  {
    id: "dsa.trees.disjoint_set",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Disjoint set (union-find)",
    description: "Track grouped elements with near-constant find and union.",
    learner_goal: "Use union-find for connected components and cycle detection.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1630,
    is_active: true
  },
  {
    id: "dsa.trees.bst_search",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Binary search tree search",
    description: "Use the BST ordering invariant to search, insert, and reason about balance.",
    learner_goal: "Search a BST in O(h) by comparing and descending, and know why balance matters.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1615,
    is_active: true
  },
  {
    id: "dsa.trees.heap_applications",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Heap applications and selection",
    description: "Apply a heap to top-k and scheduling, and choose it over a sorted vector or map.",
    learner_goal: "Use a priority_queue for top-k/scheduling and pick a heap when you repeatedly need the best.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1625,
    is_active: true
  },
  {
    id: "dsa.trees.dsu_internals",
    domain: "dsa",
    module_id: "dsa.trees",
    title: "Union-find internals",
    description: "Understand path compression and union by rank/size and their near-constant cost.",
    learner_goal: "Explain how path compression and union by rank give near-constant amortized operations.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1635,
    is_active: true
  },
  {
    id: "dsa.graphs.representation",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Graph representation",
    description: "Model graphs with adjacency lists or adjacency matrices.",
    learner_goal: "Choose an adjacency list or matrix based on density and the operations needed.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1710,
    is_active: true
  },
  {
    id: "dsa.graphs.bfs",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Breadth-first search",
    description: "Explore a graph level by level with a queue.",
    learner_goal: "Use BFS to find shortest paths in an unweighted graph.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1720,
    is_active: true
  },
  {
    id: "dsa.graphs.dfs",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Depth-first search",
    description: "Explore as deep as possible before backtracking, using recursion or a stack.",
    learner_goal: "Use DFS for reachability, cycle detection, and topological ordering.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1730,
    is_active: true
  },
  {
    id: "dsa.graphs.shortest_path",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Shortest paths",
    description: "Find minimum-cost paths with BFS, Dijkstra, or Bellman-Ford.",
    learner_goal: "Pick the right shortest-path algorithm for weighted vs unweighted graphs.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1740,
    is_active: true
  },
  {
    id: "dsa.graphs.connected_components",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Connected components",
    description: "Count and label connected components, including grid-as-graph problems.",
    learner_goal: "Find connected components with BFS/DFS and model a grid as an implicit graph.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1750,
    is_active: true
  },
  {
    id: "dsa.graphs.cycle_detection",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Cycle detection",
    description: "Detect cycles in directed and undirected graphs.",
    learner_goal: "Detect a cycle with DFS colors (directed) or union-find/parent checks (undirected).",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1760,
    is_active: true
  },
  {
    id: "dsa.graphs.topological_sort",
    domain: "dsa",
    module_id: "dsa.graphs",
    title: "Topological sort and DAGs",
    description: "Order a DAG so every edge points forward; recognize when it exists.",
    learner_goal: "Produce a topological order of a DAG and know a cycle makes one impossible.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1770,
    is_active: true
  },
  {
    id: "dsa.techniques.prefix_sums",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Prefix sums",
    description: "Precompute cumulative sums to answer range-sum queries in O(1).",
    learner_goal: "Build a prefix-sum array and use it to answer subarray-sum queries fast.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1810,
    is_active: true
  },
  {
    id: "dsa.techniques.sliding_window",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Sliding window",
    description: "Maintain a moving window over a sequence to scan subarrays in O(n).",
    learner_goal: "Use a sliding window for fixed- or variable-length subarray problems.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1820,
    is_active: true
  },
  {
    id: "dsa.techniques.greedy",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Greedy algorithms",
    description: "Make the locally optimal choice at each step when it yields a global optimum.",
    learner_goal: "Recognize when a greedy choice is provably optimal versus when it fails.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1830,
    is_active: true
  },
  {
    id: "dsa.techniques.dynamic_programming",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Dynamic programming",
    description: "Solve overlapping subproblems once and reuse results via memoization or tabulation.",
    learner_goal: "Identify optimal substructure and overlapping subproblems and write a DP recurrence.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1840,
    is_active: true
  },
  {
    id: "dsa.techniques.range_structures",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Range query structures",
    description: "Choose prefix sums, a Fenwick tree, or a segment tree by update/query needs.",
    learner_goal: "Pick a static prefix sum vs a Fenwick/segment tree based on whether values update.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1850,
    is_active: true
  },
  {
    id: "dsa.techniques.greedy_proof",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Greedy proofs and counterexamples",
    description: "Justify a greedy choice with an exchange argument and find where greedy fails.",
    learner_goal: "Argue a greedy choice is safe (exchange argument) or disprove it with a counterexample.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1860,
    is_active: true
  },
  {
    id: "dsa.techniques.dp_design",
    domain: "dsa",
    module_id: "dsa.techniques",
    title: "Designing a DP",
    description: "Define state, transition, base case, and evaluation order; memoize or tabulate.",
    learner_goal: "Specify a DP's state/transition/base/order and choose memoization vs tabulation.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1870,
    is_active: true
  },
  {
    id: "dsa.strings.manipulation",
    domain: "dsa",
    module_id: "dsa.strings",
    title: "String manipulation",
    description: "Build and transform strings efficiently, avoiding hidden copies.",
    learner_goal: "Concatenate, slice, and mutate strings without accidental O(n^2) cost.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1910,
    is_active: true
  },
  {
    id: "dsa.strings.searching",
    domain: "dsa",
    module_id: "dsa.strings",
    title: "Substring search",
    description: "Find a pattern inside text with naive scanning or KMP.",
    learner_goal: "Compare naive O(nm) search with linear-time KMP and know when each matters.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 1920,
    is_active: true
  },
  {
    id: "dsa.strings.palindrome",
    domain: "dsa",
    module_id: "dsa.strings",
    title: "Palindromes and anagrams",
    description: "Check palindromes with two pointers and anagrams with frequency counts.",
    learner_goal: "Use two pointers for palindromes and character counts for anagrams.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1930,
    is_active: true
  },
  {
    id: "dsa.strings.parsing",
    domain: "dsa",
    module_id: "dsa.strings",
    title: "Tokenizing and parsing",
    description: "Split text into tokens and parse structured input.",
    learner_goal: "Split a string on delimiters and parse fields from a line of input.",
    level: "intermediate",
    item_types: ["lesson", "quiz"],
    order_index: 1940,
    is_active: true
  },
  {
    id: "dsa.math.bit_manipulation",
    domain: "dsa",
    module_id: "dsa.math",
    title: "Bit manipulation",
    description: "Use bitwise operators and masks to test, set, and clear bits.",
    learner_goal: "Test, set, and clear individual bits and use common bit tricks.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 2010,
    is_active: true
  },
  {
    id: "dsa.math.number_theory",
    domain: "dsa",
    module_id: "dsa.math",
    title: "Number theory",
    description: "Apply GCD, primality, and modular arithmetic in algorithms.",
    learner_goal: "Compute GCD with Euclid's algorithm and reason about modular arithmetic.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 2020,
    is_active: true
  },
  {
    id: "dsa.math.combinatorics",
    domain: "dsa",
    module_id: "dsa.math",
    title: "Combinatorics",
    description: "Count arrangements and selections with permutations and combinations.",
    learner_goal: "Choose between permutations and combinations and count outcomes.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 2030,
    is_active: true
  },
  {
    id: "dsa.math.geometry",
    domain: "dsa",
    module_id: "dsa.math",
    title: "Computational geometry",
    description: "Work with points, distances, and orientation tests.",
    learner_goal: "Compute distances and use the cross product to test orientation.",
    level: "advanced",
    item_types: ["lesson", "quiz"],
    order_index: 2040,
    is_active: true
  },
  {
    id: "dsa.recursion.base_case",
    domain: "dsa",
    module_id: "dsa.recursion",
    title: "Recursion and base cases",
    description: "Write a recursive function with a base case and a step toward it.",
    learner_goal: "Identify the base case and the recursive step, and avoid infinite recursion.",
    level: "intermediate",
    item_types: ["lesson", "quiz", "bug_spotting"],
    order_index: 1510,
    is_active: true
  }
];

export const skillPrerequisitesSeed: SkillPrerequisite[] = [
  { skill_id: "cpp.program_basics.io", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.program_basics.statements_comments", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.program_basics.exit_status", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.program_basics.error_kinds", prerequisite_skill_id: "cpp.program_basics.statements_comments", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.variables", prerequisite_skill_id: "cpp.program_basics.structure", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.conversions", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.fundamental_types", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.signed_unsigned", prerequisite_skill_id: "cpp.values_types.fundamental_types", relationship_type: "recommended" },
  { skill_id: "cpp.values_types.literals", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.conditionals", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.loops", prerequisite_skill_id: "cpp.control_flow.conditionals", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.logical_operators", prerequisite_skill_id: "cpp.control_flow.conditionals", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.switch_statement", prerequisite_skill_id: "cpp.control_flow.conditionals", relationship_type: "recommended" },
  { skill_id: "cpp.control_flow.loop_invariants", prerequisite_skill_id: "cpp.control_flow.loops", relationship_type: "recommended" },
  { skill_id: "cpp.functions.basics", prerequisite_skill_id: "cpp.control_flow.loops", relationship_type: "recommended" },
  { skill_id: "cpp.functions.decomposition", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.syntax", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.references.references", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.references.pointers", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.const_correctness", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.parameter_passing", prerequisite_skill_id: "cpp.references.const_correctness", relationship_type: "recommended" },
  { skill_id: "cpp.references.lvalue_rvalue", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.return_semantics", prerequisite_skill_id: "cpp.references.references", relationship_type: "recommended" },
  { skill_id: "cpp.references.dangling", prerequisite_skill_id: "cpp.references.return_semantics", relationship_type: "recommended" },
  { skill_id: "cpp.references.pointer_const", prerequisite_skill_id: "cpp.references.const_correctness", relationship_type: "recommended" },
  { skill_id: "cpp.references.non_owning", prerequisite_skill_id: "cpp.references.pointers", relationship_type: "recommended" },
  { skill_id: "cpp.references.views", prerequisite_skill_id: "cpp.references.non_owning", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.public_private", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.const_methods_intro", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.structs_classes.invariants_intro", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.default_constructor", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.parameterized_constructor", prerequisite_skill_id: "cpp.constructors.default_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.member_initializer_list", prerequisite_skill_id: "cpp.constructors.parameterized_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.constructors.destructor_intro", prerequisite_skill_id: "cpp.constructors.default_constructor", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.copy", prerequisite_skill_id: "cpp.constructors.destructor_intro", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.move", prerequisite_skill_id: "cpp.value_semantics.copy", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.rule_of_zero_five", prerequisite_skill_id: "cpp.value_semantics.move", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.special_members", prerequisite_skill_id: "cpp.value_semantics.move", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.copy_elision", prerequisite_skill_id: "cpp.value_semantics.copy", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.operators", prerequisite_skill_id: "cpp.value_semantics.rule_of_zero_five", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.self_assignment", prerequisite_skill_id: "cpp.value_semantics.special_members", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.deep_copy", prerequisite_skill_id: "cpp.value_semantics.copy", relationship_type: "recommended" },
  { skill_id: "cpp.value_semantics.stream_insertion", prerequisite_skill_id: "cpp.value_semantics.operators", relationship_type: "recommended" },
  { skill_id: "cpp.oop.composition", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.oop.inheritance", prerequisite_skill_id: "cpp.structs_classes.public_private", relationship_type: "recommended" },
  { skill_id: "cpp.oop.virtual_polymorphism", prerequisite_skill_id: "cpp.oop.inheritance", relationship_type: "recommended" },
  { skill_id: "cpp.oop.abstract_interfaces", prerequisite_skill_id: "cpp.oop.virtual_polymorphism", relationship_type: "recommended" },
  { skill_id: "cpp.raii.resource_lifetime", prerequisite_skill_id: "cpp.constructors.destructor_intro", relationship_type: "recommended" },
  { skill_id: "cpp.raii.destructor_cleanup", prerequisite_skill_id: "cpp.raii.resource_lifetime", relationship_type: "recommended" },
  { skill_id: "cpp.raii.exception_safety_intro", prerequisite_skill_id: "cpp.raii.destructor_cleanup", relationship_type: "recommended" },
  { skill_id: "cpp.raii.ownership_boundary", prerequisite_skill_id: "cpp.raii.resource_lifetime", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.unique_ptr", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.shared_ptr", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.weak_ptr", prerequisite_skill_id: "cpp.smart_pointers.shared_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.cyclic_reference", prerequisite_skill_id: "cpp.smart_pointers.weak_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.ownership_choice", prerequisite_skill_id: "cpp.raii.ownership_boundary", relationship_type: "recommended" },
  { skill_id: "cpp.smart_pointers.ownership_transfer", prerequisite_skill_id: "cpp.smart_pointers.unique_ptr", relationship_type: "recommended" },
  { skill_id: "cpp.stl.vector", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" },
  { skill_id: "cpp.stl.string", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.map", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.set", prerequisite_skill_id: "cpp.stl.map", relationship_type: "recommended" },
  { skill_id: "cpp.stl.iterators", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.algorithms", prerequisite_skill_id: "cpp.stl.iterators", relationship_type: "recommended" },
  { skill_id: "cpp.stl.adapters", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "cpp.stl.lambdas", prerequisite_skill_id: "cpp.stl.algorithms", relationship_type: "recommended" },
  { skill_id: "cpp.templates.function_templates", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.templates.class_templates", prerequisite_skill_id: "cpp.templates.function_templates", relationship_type: "recommended" },
  { skill_id: "cpp.templates.concepts", prerequisite_skill_id: "cpp.templates.function_templates", relationship_type: "recommended" },
  { skill_id: "cpp.templates.ranges", prerequisite_skill_id: "cpp.stl.algorithms", relationship_type: "recommended" },
  { skill_id: "cpp.templates.constexpr", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.templates.if_constexpr", prerequisite_skill_id: "cpp.templates.function_templates", relationship_type: "recommended" },
  { skill_id: "cpp.templates.static_assert", prerequisite_skill_id: "cpp.templates.constexpr", relationship_type: "recommended" },
  { skill_id: "cpp.templates.multiple_params", prerequisite_skill_id: "cpp.templates.function_templates", relationship_type: "recommended" },
  { skill_id: "cpp.templates.deduction", prerequisite_skill_id: "cpp.templates.function_templates", relationship_type: "recommended" },
  { skill_id: "cpp.templates.aliases_specialization", prerequisite_skill_id: "cpp.templates.class_templates", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.error_handling", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.testing", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.debugging", prerequisite_skill_id: "cpp.tooling.testing", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.build", prerequisite_skill_id: "cpp.functions.decomposition", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.warnings", prerequisite_skill_id: "cpp.tooling.build", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.sanitizers", prerequisite_skill_id: "cpp.tooling.debugging", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.cmake", prerequisite_skill_id: "cpp.tooling.build", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.preconditions", prerequisite_skill_id: "cpp.tooling.error_handling", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.optional_expected", prerequisite_skill_id: "cpp.utilities.variant", relationship_type: "recommended" },
  { skill_id: "cpp.tooling.error_strategy", prerequisite_skill_id: "cpp.tooling.optional_expected", relationship_type: "recommended" },
  { skill_id: "cpp.concurrency.threads", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.concurrency.data_races", prerequisite_skill_id: "cpp.concurrency.threads", relationship_type: "recommended" },
  { skill_id: "cpp.concurrency.mutexes", prerequisite_skill_id: "cpp.concurrency.data_races", relationship_type: "recommended" },
  { skill_id: "cpp.concurrency.async", prerequisite_skill_id: "cpp.concurrency.threads", relationship_type: "recommended" },
  { skill_id: "cpp.utilities.file_io", prerequisite_skill_id: "cpp.program_basics.io", relationship_type: "recommended" },
  { skill_id: "cpp.utilities.chrono", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.utilities.random", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "cpp.utilities.variant", prerequisite_skill_id: "cpp.templates.class_templates", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.indexing", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.problem_solving", prerequisite_skill_id: "dsa.complexity.big_o", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.growth_rates", prerequisite_skill_id: "dsa.complexity.big_o", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.amortized", prerequisite_skill_id: "dsa.complexity.growth_rates", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.constraints", prerequisite_skill_id: "dsa.complexity.growth_rates", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.pattern_recognition", prerequisite_skill_id: "dsa.complexity.problem_solving", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.container_selection", prerequisite_skill_id: "dsa.complexity.problem_solving", relationship_type: "recommended" },
  { skill_id: "dsa.complexity.recursion_choice", prerequisite_skill_id: "dsa.recursion.base_case", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.indexing", prerequisite_skill_id: "dsa.complexity.big_o", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.traversal", prerequisite_skill_id: "dsa.arrays.indexing", relationship_type: "recommended" },
  { skill_id: "dsa.sorting.comparator", prerequisite_skill_id: "cpp.stl.algorithms", relationship_type: "recommended" },
  { skill_id: "dsa.searching.binary_search", prerequisite_skill_id: "dsa.sorting.comparator", relationship_type: "recommended" },
  { skill_id: "dsa.stacks.basic_stack", prerequisite_skill_id: "cpp.stl.adapters", relationship_type: "recommended" },
  { skill_id: "dsa.hashing.lookup", prerequisite_skill_id: "cpp.stl.map", relationship_type: "recommended" },
  { skill_id: "dsa.trees.linked_list", prerequisite_skill_id: "cpp.references.pointers", relationship_type: "recommended" },
  { skill_id: "dsa.trees.list_vs_vector", prerequisite_skill_id: "dsa.trees.linked_list", relationship_type: "recommended" },
  { skill_id: "dsa.trees.tree_terminology", prerequisite_skill_id: "dsa.recursion.base_case", relationship_type: "recommended" },
  { skill_id: "dsa.trees.traversal", prerequisite_skill_id: "dsa.recursion.base_case", relationship_type: "recommended" },
  { skill_id: "dsa.trees.heap", prerequisite_skill_id: "cpp.stl.adapters", relationship_type: "recommended" },
  { skill_id: "dsa.trees.disjoint_set", prerequisite_skill_id: "dsa.trees.traversal", relationship_type: "recommended" },
  { skill_id: "dsa.trees.bst_search", prerequisite_skill_id: "dsa.trees.traversal", relationship_type: "recommended" },
  { skill_id: "dsa.trees.heap_applications", prerequisite_skill_id: "dsa.trees.heap", relationship_type: "recommended" },
  { skill_id: "dsa.trees.dsu_internals", prerequisite_skill_id: "dsa.trees.disjoint_set", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.representation", prerequisite_skill_id: "cpp.stl.vector", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.bfs", prerequisite_skill_id: "dsa.graphs.representation", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.dfs", prerequisite_skill_id: "dsa.graphs.representation", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.shortest_path", prerequisite_skill_id: "dsa.graphs.bfs", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.connected_components", prerequisite_skill_id: "dsa.graphs.dfs", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.cycle_detection", prerequisite_skill_id: "dsa.graphs.dfs", relationship_type: "recommended" },
  { skill_id: "dsa.graphs.topological_sort", prerequisite_skill_id: "dsa.graphs.dfs", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.prefix_sums", prerequisite_skill_id: "dsa.arrays.traversal", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.sliding_window", prerequisite_skill_id: "dsa.arrays.two_pointers", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.greedy", prerequisite_skill_id: "dsa.sorting.comparator", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.dynamic_programming", prerequisite_skill_id: "dsa.recursion.base_case", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.range_structures", prerequisite_skill_id: "dsa.techniques.prefix_sums", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.greedy_proof", prerequisite_skill_id: "dsa.techniques.greedy", relationship_type: "recommended" },
  { skill_id: "dsa.techniques.dp_design", prerequisite_skill_id: "dsa.techniques.dynamic_programming", relationship_type: "recommended" },
  { skill_id: "dsa.strings.manipulation", prerequisite_skill_id: "cpp.stl.string", relationship_type: "recommended" },
  { skill_id: "dsa.strings.searching", prerequisite_skill_id: "dsa.strings.manipulation", relationship_type: "recommended" },
  { skill_id: "dsa.strings.palindrome", prerequisite_skill_id: "dsa.arrays.two_pointers", relationship_type: "recommended" },
  { skill_id: "dsa.strings.parsing", prerequisite_skill_id: "dsa.strings.manipulation", relationship_type: "recommended" },
  { skill_id: "dsa.math.bit_manipulation", prerequisite_skill_id: "cpp.values_types.variables", relationship_type: "recommended" },
  { skill_id: "dsa.math.number_theory", prerequisite_skill_id: "dsa.complexity.big_o", relationship_type: "recommended" },
  { skill_id: "dsa.math.combinatorics", prerequisite_skill_id: "dsa.math.number_theory", relationship_type: "recommended" },
  { skill_id: "dsa.math.geometry", prerequisite_skill_id: "cpp.functions.basics", relationship_type: "recommended" },
  { skill_id: "dsa.arrays.two_pointers", prerequisite_skill_id: "dsa.arrays.traversal", relationship_type: "recommended" },
  { skill_id: "dsa.recursion.base_case", prerequisite_skill_id: "cpp.structs_classes.syntax", relationship_type: "recommended" }
];

export function getSeedSkillMapPreview(): SkillMapPreviewData {
  return {
    modules: [...skillModules].sort((a, b) => a.order_index - b.order_index),
    skills: skillSeed,
    prerequisites: skillPrerequisitesSeed,
    source: "seed"
  };
}

export function getSkillsForModule(moduleId: string, skills = skillSeed) {
  return skills
    .filter((skill) => skill.module_id === moduleId && skill.is_active)
    .sort((a, b) => a.order_index - b.order_index);
}
