-- #177 append-only interview session evidence.
-- Keeps the existing one-row current-session resume model, then adds durable
-- historical attempts, code revisions, and judge-session association support.

alter table if exists public.interview_sessions
  add column if not exists session_id uuid,
  add column if not exists started_at timestamptz,
  add column if not exists completed_at timestamptz;

create table if not exists public.interview_session_attempts (
  session_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null,
  mode text not null check (mode in ('practice', 'interview')),
  duration_minutes integer not null check (duration_minutes in (35, 45, 50)),
  status text not null check (status in ('completed', 'abandoned')),
  final_phase_index integer not null default 0 check (final_phase_index between 0 and 8),
  elapsed_seconds integer not null default 0 check (elapsed_seconds >= 0),
  phase_elapsed_seconds jsonb not null default '{}'::jsonb,
  notes_by_phase jsonb not null default '{}'::jsonb,
  test_notes text not null default '',
  assistance_used boolean not null default false,
  abandonment_reason text,
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interview_session_code_revisions (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_hash text not null,
  source_bytes integer not null check (source_bytes >= 0),
  source_text text not null,
  created_at timestamptz not null default now(),
  unique (session_id, source_hash)
);

create index if not exists interview_session_attempts_user_completed_idx
  on public.interview_session_attempts(user_id, completed_at desc);

create index if not exists interview_session_attempts_problem_idx
  on public.interview_session_attempts(problem_id, completed_at desc);

create index if not exists interview_session_code_revisions_session_idx
  on public.interview_session_code_revisions(session_id, created_at desc);

alter table if exists public.interview_judge_submissions
  add column if not exists interview_session_id uuid;

create index if not exists interview_judge_submissions_session_idx
  on public.interview_judge_submissions(interview_session_id);

alter table public.interview_session_attempts enable row level security;
alter table public.interview_session_code_revisions enable row level security;

drop policy if exists "learners read own interview attempts" on public.interview_session_attempts;
create policy "learners read own interview attempts"
  on public.interview_session_attempts for select
  using (auth.uid() = user_id);

drop policy if exists "learners write own interview attempts" on public.interview_session_attempts;
create policy "learners write own interview attempts"
  on public.interview_session_attempts for insert
  with check (auth.uid() = user_id);

drop policy if exists "learners update own interview attempts" on public.interview_session_attempts;
create policy "learners update own interview attempts"
  on public.interview_session_attempts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "learners delete own interview attempts" on public.interview_session_attempts;
create policy "learners delete own interview attempts"
  on public.interview_session_attempts for delete
  using (auth.uid() = user_id);

drop policy if exists "learners read own interview revisions" on public.interview_session_code_revisions;
create policy "learners read own interview revisions"
  on public.interview_session_code_revisions for select
  using (auth.uid() = user_id);

drop policy if exists "learners write own interview revisions" on public.interview_session_code_revisions;
create policy "learners write own interview revisions"
  on public.interview_session_code_revisions for insert
  with check (auth.uid() = user_id);

drop policy if exists "learners delete own interview revisions" on public.interview_session_code_revisions;
create policy "learners delete own interview revisions"
  on public.interview_session_code_revisions for delete
  using (auth.uid() = user_id);

comment on table public.interview_session_attempts is
  'Append-only completed/abandoned interview session evidence for readiness analytics (#177).';
comment on table public.interview_session_code_revisions is
  'Meaningful learner code revisions deduplicated by source hash and attached to interview sessions (#177).';
